"""empty message

Revision ID: 3e0014fa59ca
Revises: 4a5b39003781
Create Date: 2014-09-03 16:30:20.119025

"""

# revision identifiers, used by Alembic.
revision = '3e0014fa59ca'
down_revision = '4a5b39003781'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'password')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('password', sa.VARCHAR(), autoincrement=False, nullable=False))
    ### end Alembic commands ###
