"""empty message

Revision ID: c1b2d6a2aa6
Revises: 3e0014fa59ca
Create Date: 2014-09-03 16:32:08.805429

"""

# revision identifiers, used by Alembic.
revision = 'c1b2d6a2aa6'
down_revision = '3e0014fa59ca'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('password', sa.String(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'password')
    ### end Alembic commands ###
